apiVersion: v1
kind: Pod
metadata:
  name: ghost2
spec:
  containers:
    - name: "nginx"
      image: "nginx:1.9.12"
      ports:
        - containerPort: 80
    - name: "ghost"
      image: "kelseyhightower/ghost:0.7.7"
